# Generated by Django 5.1.6 on 2025-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='New', max_length=20)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_data', models.DateTimeField(blank=True, null=True)),
                ('last_modification_data', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('language_version', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('position_schedule_codes', models.JSONField(blank=True, null=True)),
                ('employment_period', models.JSONField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('required_experiences', models.JSONField(blank=True, null=True)),
                ('offered_remuneration_package', models.JSONField(blank=True, null=True)),
                ('required_driving_licenses', models.JSONField(blank=True, null=True)),
                ('position_languages', models.JSONField(blank=True, null=True)),
                ('working_language_codes', models.JSONField(blank=True, null=True)),
                ('employer', models.JSONField(blank=True, null=True)),
                ('application_instruction', models.JSONField(blank=True, null=True)),
                ('person_contacts', models.JSONField(blank=True, null=True)),
                ('last_application_date', models.DateTimeField(blank=True, null=True)),
                ('travel_preference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='categories',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position_offering_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default='en', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='position_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
