# Generated by Django 5.1.6 on 2025-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_jobdocument_rename_categories_job_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
