# Generated by Django 5.1.6 on 2025-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
