# Generated by Django 5.1.6 on 2025-04-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdocument',
            name='creation_data',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='last_application_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='last_modification_data',
            field=models.CharField(blank=True, null=True),
        ),
    ]
