# Generated by Django 5.1.6 on 2025-04-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_alter_jobdocument_creation_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_categories',
        ),
        migrations.RemoveField(
            model_name='job',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_map',
        ),
        migrations.RemoveField(
            model_name='job',
            name='number_of_posts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position_schedule',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
