# Generated by Django 5.1.6 on 2025-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_remove_job_created_at_remove_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='json_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
