# Generated by Django 5.1.6 on 2025-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_job_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='json_data',
            field=models.JSONField(),
        ),
    ]
