# Generated by Django 5.1.6 on 2025-04-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_alter_job_json_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDocument',
            new_name='JobData',
        ),
    ]
