# Generated by Django 5.1.6 on 2025-04-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_rename_jobdocument_jobdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='application_instruction',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='creation_data',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='employment_period',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='language_version',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='last_application_date',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='last_modification_data',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='offered_remuneration_package',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='person_contacts',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='position_languages',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='position_schedule_codes',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='required_driving_licenses',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='required_experiences',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='travel_preference',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='working_language_codes',
        ),
        migrations.AddField(
            model_name='jobdata',
            name='available_languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='creation_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employer_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='json_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='number_of_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
