# Generated by Django 5.1.6 on 2025-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_remove_jobdata_application_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='employer_legal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='eures_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='job_categories_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='last_modification_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='position_offering_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='position_schedule_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
