# Generated by Django 5.1.6 on 2025-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_remove_jobdata_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='available_languages',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='employer_legal_id',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='score',
        ),
        migrations.AddField(
            model_name='jobdata',
            name='connection_point_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_address_lines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_emails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_fax_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_given_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_mobile_telephone_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_telephone_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='contact_web_profiles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employment_period_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employment_period_end_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='employment_period_start_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='language_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location_address_lines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='location_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='position_offering_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
