# Generated by Django 5.1.6 on 2025-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_remove_job_json_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='contact_emails',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='contact_telephone_numbers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
