# Generated by Django 5.1.6 on 2025-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_alter_jobdata_contact_emails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='title',
        ),
    ]
