# Generated by Django 5.1.6 on 2025-04-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_rename_employer_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='employer',
        ),
    ]
