# Generated by Django 5.1.6 on 2025-04-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_remove_jobdata_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='connection_point_id',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='contact_fax_numbers',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='contact_web_profiles',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='employment_period_description',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='employment_period_end_date',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='employment_period_start_date',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='eures_flag',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='job_categories_codes',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='language_version',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='last_modification_date',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='number_of_posts',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='position_offering_code',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='position_schedule_codes',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='source',
        ),
    ]
