# Generated by Django 5.1.6 on 2025-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0019_rename_jobinfo_jobdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location_address_lines', models.JSONField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_website', models.URLField(blank=True, null=True)),
                ('employer_description', models.TextField(blank=True, null=True)),
                ('contact_given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_region', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address_lines', models.JSONField(blank=True, null=True)),
                ('contact_telephone_numbers', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_mobile_telephone_numbers', models.JSONField(blank=True, null=True)),
                ('contact_emails', models.CharField(blank=True, max_length=200, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='JobData',
        ),
    ]
