# Generated by Django 5.1.6 on 2025-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0021_rename_jobinfo_jobdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='contact_city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='contact_family_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='contact_given_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='contact_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='location_city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='location_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
