# Generated by Django 5.1.6 on 2025-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0022_alter_jobdata_contact_city_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobMainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('givenName', models.CharField(blank=True, max_length=255, null=True)),
                ('familyName', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='json_data',
        ),
    ]
