# Generated by Django 5.1.6 on 2025-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0023_jobjson_jobmaindata_remove_jobdata_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobjson',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobjson',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobmaindata',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
