# Generated by Django 5.1.6 on 2025-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0024_jobjson_job_id_jobjson_title_jobmaindata_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='organisation_size_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
