# Generated by Django 5.1.6 on 2025-04-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0025_jobdata_organisation_size_code_jobdata_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdata',
            old_name='organisation_size_code',
            new_name='employer_organisation_size',
        ),
    ]
