# Generated by Django 5.1.6 on 2025-04-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0026_rename_organisation_size_code_jobdata_employer_organisation_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobMainData',
            new_name='JobInfo',
        ),
    ]
