# Generated by Django 5.1.6 on 2025-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0027_rename_jobmaindata_jobinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobData',
            new_name='JobFullInfo',
        ),
    ]
