# Generated by Django 5.1.6 on 2025-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0028_rename_jobdata_jobfullinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='company',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='country',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='description',
            field=models.CharField(blank=True, max_length=725, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='email',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='familyName',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='givenName',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='link',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='salary',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='title',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='website',
            field=models.CharField(blank=True, max_length=525, null=True),
        ),
    ]
