# Generated by Django 5.1.6 on 2025-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0029_alter_jobinfo_company_alter_jobinfo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
