# Generated by Django 5.1.6 on 2025-04-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0030_alter_jobinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfullinfo',
            name='location_country_code',
        ),
    ]
