# Generated by Django 5.1.6 on 2025-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0031_remove_jobfullinfo_location_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=525, null=True)),
                ('company', models.CharField(blank=True, max_length=525, null=True)),
                ('website', models.CharField(blank=True, max_length=525, null=True)),
                ('country', models.CharField(blank=True, max_length=525, null=True)),
                ('full_name', models.CharField(blank=True, max_length=525, null=True)),
                ('givenName', models.CharField(blank=True, max_length=525, null=True)),
                ('familyName', models.CharField(blank=True, max_length=525, null=True)),
                ('salary', models.CharField(blank=True, max_length=525, null=True)),
                ('email', models.CharField(blank=True, max_length=525, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=525, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=525, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
            ],
        ),
    ]
